# Generated by Django 2.2.11 on 2020-03-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
import utils.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20200223_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0007_auto_20200131_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalNotice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('type', utils.django.fields.ChoiceField(choices=[('all', '전체 공지'), ('team', '팀별 공지'), ('project', '프로젝트 공지')], help_text='`all`: 전체 공지\n<br>`team`: 팀별 공지\n<br>`project`: 프로젝트 공지\n', max_length=10, verbose_name='공지유형')),
                ('title', models.CharField(max_length=100, verbose_name='공지명')),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='일시')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='예상 진행시간')),
                ('address1', models.CharField(blank=True, help_text='도로명/지번 주소', max_length=200, verbose_name='주소')),
                ('address2', models.CharField(blank=True, help_text='건물명/층/호수/상세장소 등', max_length=100, verbose_name='상세주소')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.Team', verbose_name='팀')),
            ],
            options={
                'verbose_name': 'historical 공지',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttendance',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('vote', utils.django.fields.ChoiceField(choices=[('unselected', '미선택'), ('attend', '참여'), ('absent', '미참여'), ('late', '지각')], default='unselected', help_text='`unselected`: 미선택\n<br>`attend`: 참여\n<br>`absent`: 미참여\n<br>`late`: 지각\n', max_length=15, verbose_name='투표')),
                ('result', models.CharField(blank=True, choices=[('unselected', '미선택'), ('attend', '참여'), ('absent', '미참여'), ('late', '지각')], max_length=15, verbose_name='실제 참석결과')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notice.Notice', verbose_name='공지')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'historical 공지 참석 투표',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
