# Generated by Django 2.2.11 on 2020-03-23 03:23

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0011_auto_20200322_2129"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="_history_user",),
        migrations.RemoveField(model_name="attendance", name="deleted",),
        migrations.RemoveField(
            model_name="historicalattendance", name="_history_user",
        ),
        migrations.RemoveField(model_name="historicalattendance", name="deleted",),
        migrations.RemoveField(model_name="historicalnotice", name="_history_user",),
        migrations.RemoveField(model_name="historicalnotice", name="deleted",),
        migrations.RemoveField(model_name="notice", name="_history_user",),
        migrations.RemoveField(model_name="notice", name="deleted",),
        migrations.AddField(
            model_name="attendance",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
