# Generated by Django 2.2.12 on 2020-05-06 08:11
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from events.lol.models import Position


def forwards_func(apps, schema_editor):
    for name, value in Position.CHOICES_NAME:
        Position.objects.get_or_create(name=name)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LOLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(
                    choices=[('unranked1', '언랭1'), ('unranked2', '언랭2'), ('unranked3', '언랭3'), ('unranked4', '언랭4'),
                             ('unranked5', '언랭5'), ('iron1', '아이언1'), ('iron2', '아이언2'), ('iron3', '아이언3'),
                             ('iron4', '아이언4'), ('iron5', '아이언5'), ('bronze1', '브론즈1'), ('bronze2', '브론즈2'),
                             ('bronze3', '브론즈3'), ('bronze4', '브론즈4'), ('bronze5', '브론즈5'), ('silver1', '실버1'),
                             ('silver2', '실버2'), ('silver3', '실버3'), ('silver4', '실버4'), ('silver5', '실버5'),
                             ('gold1', '골드1'), ('gold2', '골드2'), ('gold3', '골드3'), ('gold4', '골드4'), ('gold5', '골드5'),
                             ('platinum1', '플래티넘1'), ('platinum2', '플래티넘2'), ('platinum3', '플래티넘3'),
                             ('platinum4', '플래티넘4'), ('platinum5', '플래티넘5'), ('diamond1', '다이아몬드1'),
                             ('diamond2', '다이아몬드2'), ('diamond3', '다이아몬드3'), ('diamond4', '다이아몬드4'),
                             ('diamond5', '다이아몬드5')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(choices=[('top', '탑'), ('jungle', '정글'), ('mid', '미드'), ('adc', '원딜'), ('sup', '서폿')],
                                  max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                                                           null=True)),
                ('drip', models.CharField(max_length=100, verbose_name='드립을 쳐주세요')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_point_set',
                                            to='lol.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_set',
                                             to='lol.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='position_set',
            field=models.ManyToManyField(blank=True, to='lol.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='lol.LOLTeam'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
