# Generated by Django 2.1.5 on 2019-02-01 03:53

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Team = apps.get_model('members', 'Team')
    Period = apps.get_model('members', 'Period')

    team_name_list = ['백엔드', 'iOS', '안드로이드', '디자인']
    for team_name in team_name_list:
        Team.objects.using(db_alias).create(name=team_name)

    period_number_list = [1, 2, 3, 4, 5, 6, 7]
    for period_number in period_number_list:
        Period.objects.using(db_alias).create(number=period_number)


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Team = apps.get_model('members', 'Team')
    Period = apps.get_model('members', 'Period')

    Team.objects.using(db_alias).all().delete()
    Period.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
