# Generated by Django 2.2.4 on 2019-08-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_auto_20190826_1848"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("name",),
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
            },
        ),
    ]
