# Generated by Django 2.2.5 on 2019-09-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20190826_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userperiodteam',
            unique_together={('user', 'period', 'team')},
        ),
    ]
