# Generated by Django 2.2.9 on 2020-02-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_emailvalidation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name', '-pk'), 'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='members_use_usernam_82d39a_idx'),
        ),
    ]
