# Generated by Django 2.2.10 on 2020-02-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_auto_20200201_1638"),
    ]

    operations = [
        migrations.AddField(
            model_name="userperiodteam",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="해당기수 중도 탈퇴시 False처리", verbose_name="기수 활동여부"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userperiodoutcount", unique_together=set(),
        ),
        migrations.AlterUniqueTogether(name="userperiodteam", unique_together=set(),),
        migrations.AddIndex(
            model_name="userperiodoutcount",
            index=models.Index(fields=["count"], name="members_use_count_2493bd_idx"),
        ),
        migrations.AddIndex(
            model_name="userperiodteam",
            index=models.Index(
                fields=["is_active"], name="members_use_is_acti_228b3a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userperiodoutcount",
            constraint=models.UniqueConstraint(
                fields=("user", "period"), name="unique_user_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="userperiodteam",
            constraint=models.UniqueConstraint(
                fields=("user", "period", "team"), name="unique_user_period_team"
            ),
        ),
    ]
