# Generated by Django 2.2.11 on 2020-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_auto_20200223_1726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="period_set",
            field=models.ManyToManyField(
                blank=True,
                through="members.UserPeriodTeam",
                to="members.Period",
                verbose_name="활동기수",
            ),
        ),
    ]
