# Generated by Django 2.1.5 on 2019-02-01 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='스터디명')),
            ],
            options={
                'verbose_name': '스터디',
                'verbose_name_plural': '스터디 목록',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='StudyMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(verbose_name='시작일시')),
                ('end_at', models.DateTimeField(verbose_name='종료일시')),
                ('location', models.CharField(max_length=200, verbose_name='장소')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_set', related_query_name='meeting', to='study.Study', verbose_name='스터디')),
            ],
            options={
                'verbose_name': '스터디모임',
                'verbose_name_plural': '스터디모임 목록',
            },
        ),
        migrations.CreateModel(
            name='StudyMeetingFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='금액')),
            ],
            options={
                'verbose_name': '스터디모임 벌금',
                'verbose_name_plural': '스터디모임 벌금 목록',
            },
        ),
        migrations.CreateModel(
            name='StudyMeetingFineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='벌금 카테고리명')),
            ],
            options={
                'verbose_name': '스터디모임 벌금 카테고리',
                'verbose_name_plural': '스터디모임 벌금 카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='StudyMeetingUserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_user_activity_set', related_query_name='meeting_user_activity', to='study.StudyMeeting', verbose_name='스터디 모임')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_user_activity_set', related_query_name='meeting_user_activity', to=settings.AUTH_USER_MODEL, verbose_name='스터디원')),
            ],
            options={
                'verbose_name': '스터디모임 유저활동정보',
                'verbose_name_plural': '스터디모임 유저활동정보 목록',
            },
        ),
        migrations.CreateModel(
            name='StudyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('late_fine', models.PositiveIntegerField(default=0, verbose_name='벌금')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', related_query_name='membership', to='study.Study', verbose_name='스터디')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', related_query_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='스터디원')),
            ],
            options={
                'verbose_name': '스터디원 정보',
                'verbose_name_plural': '스터디원 정보 목록',
            },
        ),
        migrations.AddField(
            model_name='studymeetingfine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fine_set', related_query_name='fine', to='study.StudyMeetingFineCategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='studymeetingfine',
            name='meeting_user_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_set', related_query_name='fine', to='study.StudyMeetingUserActivity', verbose_name='스터디 모임 활동정보'),
        ),
        migrations.AddField(
            model_name='study',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='study_set', related_query_name='study', through='study.StudyMembership', to=settings.AUTH_USER_MODEL, verbose_name='스터디원 목록'),
        ),
        migrations.AddField(
            model_name='study',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_set', related_query_name='study', to='members.Period', verbose_name='기수'),
        ),
        migrations.AddField(
            model_name='study',
            name='team_set',
            field=models.ManyToManyField(related_name='study_set', related_query_name='study', to='members.Team', verbose_name='팀 목록'),
        ),
    ]
